name: s_state
description: Simple and quick state management
version: 0.0.1+1
homepage: "https://github.com/sbaskoy/s_state"
repository: "https://github.com/sbaskoy/s_state"



topics:
  - state
  - statemanagement

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
